apiVersion: apps/v1
kind: Deployment
metadata:
  name: aboutpage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: about
  template:
    metadata:
      labels:
        app: about
    spec:
      containers:
      - name: aboutpage-con
        image: curion22/aboutpage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aboutpage-service
spec:
  selector:
    app: about
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
        
