apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contact
  template:
    metadata:
      labels:
        app: contact
    spec:
      containers:
      - name: contactpage-con
        image: curion22/contactpage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: contactpage-service
spec:
  selector:
    app: contact
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
