apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: my-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: homepage-con
        image: curion22/homepage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-service
spec:
  selector:
    app: home
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
